/*
 * Generated by MTK SP DrvGen Version: 3.5.160809 for MT6765.
 * 2023-08-23 20:59:31
 * Do Not Modify The File.
 * Copyright Mediatek Inc. (c) 2016.
*/

#ifndef __CUST_ADC_H
#define __CUST_ADC_H

#define AUXADC_TEMPERATURE_CHANNEL			0
#define AUXADC_TEMPERATURE1_CHANNEL			1
#define AUXADC_BATTERY_VOLTAGE_CHANNEL			2
#define AUXADC_ADC_FDD_RF_PARAMS_DYNAMIC_CUSTOM_CH_CHANNEL			3


#endif /* __CUST_ADC_H */
